### ISSUE TITLE
Application returning 404 after docker-compose up

### ISSUE THREAD

**Issue by Flavyoo** [PHPExpertsInc/dockerize-php#15]
I have installed the latest version of dockerize-php and then ran docker-compose up. Unfortunately this results in the app throwing a 404.

I was able to fix this by modifying the default nginx file and setting the root directive to `root /var/www/public;` instead of `root /var/www/web;`

I'm not sure if this is specific to my app setup or if this is a mistake in the nginx configuration.

**Comment by hopeseekr** [comment]
Yeah that's why I version bumped it from v6.0.0 to v7.0.0 because I changed the default nginx path from `web/` to `public/` to be more in line with PHP standards. Magento, Laravel and Symfony all use `public/`.
